# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 09:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_monthjournal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthjournal',
            options={'verbose_name': 'Місячний журнал', 'verbose_name_plural': 'Місячні журнали'},
        ),
    ]
